import { useState } from "react";
import { useExam } from "@/context/ExamContext";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Plus, Pencil, Trash2, Loader2 } from "lucide-react";

export default function SubjectManagement() {
  const { exams, addSubject, deleteSubject } = useExam();
  const [open, setOpen] = useState(false);
  const [selectedExam, setSelectedExam] = useState<string>("");
  const [formData, setFormData] = useState({ subjectName: "" });

  // Fetch subjects for the selected exam
  const { data: subjects = [], isLoading } = useQuery({
    queryKey: ["subjects", selectedExam],
    queryFn: async () => {
      if (!selectedExam || selectedExam === "all") return [];
      const res = await fetch(`/api/exams/${selectedExam}/subjects`);
      if (!res.ok) throw new Error("Failed to fetch subjects");
      return res.json();
    },
    enabled: !!selectedExam && selectedExam !== "all",
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (formData.subjectName.trim() && selectedExam) {
      addSubject(selectedExam, {
        id: "", // ID generated by DB
        examId: selectedExam,
        subjectName: formData.subjectName,
      });
      setFormData({ subjectName: "" });
      setOpen(false);
    }
  };

  const handleDelete = (id: string) => {
    if (confirm("Are you sure you want to delete this subject?")) {
      deleteSubject(id);
    }
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-slate-900">
          Subject Management
        </h2>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button className="bg-blue-600 hover:bg-blue-700" disabled={!selectedExam || selectedExam === "all"}>
              <Plus size={20} className="mr-2" />
              New Subject
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Add New Subject</DialogTitle>
              <DialogDescription>Add a subject to the selected exam</DialogDescription>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label>Selected Exam</Label>
                <div className="p-2 bg-slate-100 rounded border border-slate-200 text-slate-700">
                  {exams.find(e => e.id === selectedExam)?.examName || "None"}
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="subjectName">Subject Name</Label>
                <Input
                  id="subjectName"
                  placeholder="e.g., Physics"
                  value={formData.subjectName}
                  onChange={(e) =>
                    setFormData({ ...formData, subjectName: e.target.value })
                  }
                  required
                />
              </div>
              <Button type="submit" className="w-full">
                Add Subject
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <div className="bg-white rounded-lg p-4">
        <Label htmlFor="examFilter">Select Exam to Manage Subjects</Label>
        <Select
          value={selectedExam}
          onValueChange={(v) => setSelectedExam(v)}
        >
          <SelectTrigger id="examFilter" className="mt-2">
            <SelectValue placeholder="Select an Exam" />
          </SelectTrigger>
          <SelectContent>
            {exams.map((exam) => (
              <SelectItem key={exam.id} value={exam.id}>
                {exam.examName}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Subject Name</TableHead>
              <TableHead>Exam</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {!selectedExam ? (
              <TableRow>
                <TableCell
                  colSpan={3}
                  className="text-center py-8 text-slate-500"
                >
                  Please select an exam to view subjects.
                </TableCell>
              </TableRow>
            ) : isLoading ? (
              <TableRow>
                <TableCell colSpan={3} className="text-center py-8">
                  <Loader2 className="w-6 h-6 animate-spin mx-auto text-blue-600" />
                </TableCell>
              </TableRow>
            ) : subjects.length === 0 ? (
              <TableRow>
                <TableCell
                  colSpan={3}
                  className="text-center py-8 text-slate-500"
                >
                  No subjects found for this exam.
                </TableCell>
              </TableRow>
            ) : (
              subjects.map((subject: any) => {
                const exam = exams.find((e) => e.id === subject.examId);
                return (
                  <TableRow key={subject.id}>
                    <TableCell className="font-medium">
                      {subject.subjectName}
                    </TableCell>
                    <TableCell>{exam?.examName || "Unknown"}</TableCell>
                    <TableCell className="text-right space-x-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        className="text-blue-600 hover:text-blue-700"
                      >
                        <Pencil size={16} />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="text-red-600 hover:text-red-700"
                        onClick={() => handleDelete(subject.id)}
                      >
                        <Trash2 size={16} />
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
      </Card>
    </div>
  );
}
